# Generated by Django 4.2.1 on 2023-09-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0004_exam_block_exam_class_name_exam_time_alter_exam_date_and_more'),
        ('web_librarian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('return_day', models.DateField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_librarian.books')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
            ],
        ),
    ]
