# Generated by Django 4.2.1 on 2023-09-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20)),
                ('publication_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.librarycategory')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryItemCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('A', 'Available'), ('L', 'Loaned'), ('R', 'Researved')], max_length=1)),
                ('last_loan_date', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.libraryitem')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School_blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('admission_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('school_block', models.CharField(max_length=200)),
                ('class_block', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(max_length=200)),
                ('prevoius_school', models.CharField(max_length=200)),
                ('prevoius_grade', models.CharField(max_length=200)),
                ('profile_picture', models.CharField(max_length=200)),
                ('guardian_first_name', models.CharField(max_length=200)),
                ('guardian_middle_name', models.CharField(max_length=200)),
                ('guardian_last_name', models.CharField(max_length=200)),
                ('guardian_phone_number', models.CharField(max_length=200)),
                ('guardian_profile_picture', models.CharField(max_length=200)),
                ('guardian_alternative_mobile_number', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('previous_school', models.CharField(max_length=200)),
                ('teaching_subjects', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_day', models.CharField(max_length=20)),
                ('class_period', models.CharField(max_length=20)),
                ('class_room', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.subject')),
                ('teacher', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserved', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled'), ('A', 'Approved')], max_length=1)),
                ('item_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.libraryitemcopy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
            ],
        ),
        migrations.AddField(
            model_name='libraryitemcopy',
            name='last_borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField()),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.assignment')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(max_length=2)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.subject')),
            ],
        ),
        migrations.CreateModel(
            name='class_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher')),
                ('school_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.school_blocks')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.subject'),
        ),
    ]
