# Generated by Django 4.2.1 on 2023-09-16 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('link', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_combinations', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_combination', models.CharField(max_length=255)),
                ('School', models.CharField(max_length=255)),
                ('posted_by', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('Date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportationStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_block',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_period',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='class_block',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.school_blocks'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_produced',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Surtday', 'Surtday'), ('Sunday', 'Sunday')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.school_blocks'),
        ),
        migrations.CreateModel(
            name='TransportationStopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.transportationroute')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.transportationstop')),
            ],
        ),
        migrations.AddField(
            model_name='transportationroute',
            name='stops',
            field=models.ManyToManyField(through='web_super_admin.TransportationStopOrder', to='web_super_admin.transportationstop'),
        ),
        migrations.CreateModel(
            name='TransportationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.transportationroute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student')),
            ],
        ),
        migrations.CreateModel(
            name='class_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher')),
                ('school_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher'),
        ),
    ]
