# Generated by Django 4.2.1 on 2023-09-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0002_elearning_message_opportunities_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.student'),
        ),
    ]
