# Generated by Django 4.2.1 on 2023-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0006_alter_staff_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_profile_picture',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
