# Generated by Django 4.2.1 on 2023-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0007_alter_student_guardian_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_profile_picture',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
