# Generated by Django 4.2.1 on 2023-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0008_alter_staff_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_profile_picture',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='a.png', upload_to='upload/'),
        ),
    ]
