# Generated by Django 4.2.1 on 2023-09-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0009_alter_staff_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
