# Generated by Django 4.2.7 on 2023-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0010_student_confirm_password_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prevoius_grade',
            new_name='previous_grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prevoius_school',
            new_name='previous_school',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='start_date',
            new_name='joining_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='role',
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
