# Generated by Django 4.2.7 on 2023-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0011_rename_prevoius_grade_student_previous_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
        ),
    ]
