# Generated by Django 4.2.7 on 2023-12-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0013_staff_staff_number_teacher_teacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('Librarian', 'Librarian'), ('Accountant', 'Accountant'), ('Cooker', 'Cooker'), ('Casual Work', 'Casual Work')], max_length=200, null=True),
        ),
    ]
