# Generated by Django 4.2.7 on 2023-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0016_super_admin_user_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_user',
            name='Registration_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_user',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
