# Generated by Django 4.2.7 on 2023-12-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0019_school_county_school_contact_school_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='super_admin_user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
