# Generated by Django 4.2.7 on 2023-12-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0020_school_country_super_admin_user_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Super_Admin_User',
        ),
    ]
