# Generated by Django 4.2.7 on 2024-01-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_admin_user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='a.png', null=True, upload_to='upload/'),
        ),
    ]
