# Generated by Django 4.2.1 on 2023-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject_combination', models.CharField(max_length=255)),
                ('School', models.CharField(max_length=255)),
                ('posted_by', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('Date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
