# Generated by Django 4.2.1 on 2023-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0005_staff_start_date_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
