# Generated by Django 4.2.1 on 2023-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0006_staff_end_date_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
