# Generated by Django 4.2.1 on 2023-09-05 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0008_elearning_remove_notice_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('class_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher')),
            ],
        ),
    ]
