# Generated by Django 4.2.1 on 2023-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0009_class_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_create',
            old_name='class_block',
            new_name='school_block',
        ),
        migrations.AddField(
            model_name='class_create',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
