# Generated by Django 4.2.1 on 2023-09-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0011_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
