# Generated by Django 4.2.1 on 2023-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0012_rename_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
