# Generated by Django 4.2.1 on 2023-09-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0013_alter_message_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_period',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='timetable',
            name='activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.school_blocks'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='date_produced',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Surtday', 'Surtday'), ('Sunday', 'Sunday')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_create'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.teacher'),
        ),
    ]
