# Generated by Django 4.2.1 on 2023-09-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0014_remove_timetable_class_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_section',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='target_class',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AddField(
            model_name='class_block',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
    ]
