# Generated by Django 4.2.1 on 2023-09-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_super_admin', '0017_alter_timetable_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_block',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.class_block'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_super_admin.school_blocks'),
        ),
    ]
